export enum WarcraftClass {
  Unknown = 99,
  DeathKnight,
  DemonHunter,
  Druid,
  Evoker,
  Hunter,
  Mage,
  Monk,
  Paladin,
  Priest,
  Rogue,
  Shaman,
  Warlock,
  Warrior,
}

export enum WarcraftClassSpecialization {
  BloodDeathKnight = 250,
  FrostDeathKnight = 251,
  UnholyDeathKnight = 252,
  HavocDemonHunter = 577,
  VegeanceDemonHunter = 581,
  BalanceDruid = 102,
  FeralDruid = 103,
  GuardianDruid = 104,
  RestorationDruid = 105,
  AugmentationEvoker = 1473,
  DevastationEvoker = 1467,
  PreservationEvoker = 1468,
  BeastMasteryHunter = 253,
  MarksmanshipHunter = 254,
  SurvivalHunter = 255,
  ArcaneMage = 62,
  FireMage = 63,
  FrostMage = 64,
  BrewmasterMonk = 268,
  MistweaverMonk = 270,
  WindwalkerMonk = 269,
  HolyPaladin = 65,
  ProtectionPaladin = 66,
  RetributionPaladin = 70,
  DisciplinePriest = 256,
  HolyPriest = 257,
  ShadowPriest = 258,
  AssassinationRogue = 259,
  OutlawRogue = 260,
  SubtletyRogue = 261,
  ElementalShaman = 262,
  EnhancementShaman = 263,
  RestorationShaman = 264,
  AfflictionWarlock = 265,
  DemonologyWarlock = 266,
  DestructionWarlock = 267,
  ArmsWarrior = 71,
  FuryWarrior = 72,
  ProtectionWarrior = 73,
}

export enum WarcraftFaction {
  Horde,
  Alliance,
}

export enum WarcraftRace {}
