name: obscure-ci
on:
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
jobs:
  ci-cd-build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup
        run: |
          yarn install
          yarn lerna bootstrap
          yarn workspace @obscure/electron rebuild
      - name: Test
        run: |
          yarn test:ui
      - name: Build
        run: |
          yarn build --win
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: wow-combat-parser
          path: releases

